# -*- coding: utf-8 -*-
"""BD_LiveScore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HH7rsujf5yeIbzsecG9asIUD5L9D5QhD
"""

import requests
import pandas as pd
from datetime import datetime, timedelta
import time
import random
from google.colab import files

print("Iniciando a extração via API Oculta do LiveScore...")

# 1. Definir o período de datas (De 01/01/2025 até Hoje)
data_inicial = datetime(2025, 1, 1)
data_final = datetime.now()

# Gera uma lista com todas as datas nesse intervalo
datas_para_raspar = [data_inicial + timedelta(days=x) for x in range((data_final - data_inicial).days + 1)]

# Headers básicos para a API não nos rejeitar
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    'Accept': '*/*',
    'Origin': 'https://www.livescore.com',
    'Referer': 'https://www.livescore.com/'
}

todos_os_jogos = []

print(f"Total de dias para processar: {len(datas_para_raspar)} dias.\n")

# 2. Loop de Raspagem na API
for data_obj in datas_para_raspar:
    # A API do LiveScore usa o formato YYYYMMDD
    data_str = data_obj.strftime('%Y%m%d')
    data_legivel = data_obj.strftime('%Y-%m-%d')

    # URL da API (-3 é o fuso horário para alinhar com o Brasil/América do Sul)
    url_api = f"https://prod-public-api.livescore.com/v1/api/app/date/soccer/{data_str}/-3"

    print(f"Coletando dados do dia: {data_legivel} ... ", end="")

    try:
        response = requests.get(url_api, headers=headers, timeout=15)

        if response.status_code == 200:
            # A mágica acontece aqui: pegamos os dados puros em JSON
            dados_json = response.json()
            jogos_do_dia = 0

            # O JSON é organizado por "Stages" (Ligas) e depois "Events" (Jogos)
            ligas = dados_json.get('Stages', [])

            for liga in ligas:
                nome_pais = liga.get('Cnm', 'Desconhecido')
                nome_liga = liga.get('Snm', 'Desconhecida')
                liga_completa = f"{nome_pais} - {nome_liga}"

                jogos = liga.get('Events', [])

                for jogo in jogos:
                    # 'Eps' = Event Progress Status ('FT' significa Full Time / Finalizado)
                    status = jogo.get('Eps', '')

                    if status == 'FT':
                        try:
                            # Extrai os nomes (T1 = Mandante, T2 = Visitante)
                            home_team = jogo['T1'][0]['Nm']
                            away_team = jogo['T2'][0]['Nm']

                            # Extrai o placar (Tr1 = Gols Mandante, Tr2 = Gols Visitante)
                            gols_home = jogo.get('Tr1', '')
                            gols_away = jogo.get('Tr2', '')

                            todos_os_jogos.append({
                                'Data': data_legivel,
                                'Liga': liga_completa,
                                'HomeTeam': home_team,
                                'AwayTeam': away_team,
                                'FTHG': gols_home,
                                'FTAG': gols_away
                            })
                            jogos_do_dia += 1
                        except (KeyError, IndexError):
                            # Pula se o jogo estiver com dados corrompidos no servidor
                            pass

            print(f"OK ({jogos_do_dia} jogos)")
        else:
            print(f"Falha (Status {response.status_code})")

    except Exception as e:
        print(f"Erro de conexão: {e}")

    # Pausa super curta, pois APIs suportam requisições mais rápidas que páginas HTML
    time.sleep(random.uniform(0.5, 1.5))

# 3. Processar e Exportar os Dados
print("\nProcessamento concluído! Organizando o Banco de Dados...")
df = pd.DataFrame(todos_os_jogos)

if not df.empty:
    # Limpeza básica para garantir que gols são números
    df = df[df['FTHG'] != '']
    df['FTHG'] = pd.to_numeric(df['FTHG'], errors='coerce').fillna(0).astype(int)
    df['FTAG'] = pd.to_numeric(df['FTAG'], errors='coerce').fillna(0).astype(int)

    nome_arquivo = 'base_livescore_api_2025_hoje.csv'
    df.to_csv(nome_arquivo, index=False)

    print(f"🎉 SUCESSO ABSOLUTO! Total de jogos capturados do mundo todo: {len(df)}")
    print("Iniciando o download do arquivo CSV...")
    files.download(nome_arquivo)
else:
    print("\nNenhum jogo finalizado foi encontrado.")