name: Automação Diária LayAway5

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: 

jobs:
  atualizar-base:
    runs-on: ubuntu-latest

    steps:
      - name: Puxar os arquivos do repositório
        uses: actions/checkout@v4

      - name: Preparar o computador virtual com Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar as ferramentas (Pandas e Requests)
        run: pip install pandas requests

      - name: Executar o Robô de Scraping e Telegram
        run: |
          export TELEGRAM_TOKEN="${{ secrets.TELEGRAM_TOKEN }}"
          export TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}"
          python update_scores.py

      - name: Salvar a planilha de volta no GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add base_livescore_api_2025_hoje.csv
          git commit -m "Atualização automática: Novos jogos adicionados" || echo "Nenhuma mudança para commitar"
          git push
